#[Big Shot Lib] Cached dependency versions. Run the updateDependencyVersions task to update them all to latest.
#Wed Jul 15 11:40:34 MDT 2026
fabric-api=qPNxv5qZ
fabric-language-kotlin=Pd0xrHCw
fabric-loader=0.19.3
