#[Big Shot Lib] Cached dependency versions. Run the updateDependencyVersions task to update them all to latest.
#Thu Jul 23 15:25:33 MDT 2026
fabric-api=qPNxv5qZ
fabric-language-kotlin=bdhiINYC
fabric-loader=0.19.3
