#[Big Shot Lib] Cached dependency versions. Run the updateDependencyVersions task to update them all to latest.
#Wed Jul 15 16:56:57 MDT 2026
kotlin-for-forge=WSKgpZoB
neoforge-loader=21.10.64
sodium=PdQpfqPZ
