#[Big Shot Lib] Cached dependency versions. Run the updateDependencyVersions task to update them all to latest.
#Tue Jul 14 21:28:05 MDT 2026
fabric-api=Kr4WG5mG
fabric-language-kotlin=Pd0xrHCw
fabric-loader=0.19.3
sodium=2Yom1N68
