package net.typho.big_shot_lib.api.client.rendering.textures

import net.typho.big_shot_lib.api.client.rendering.util.GlNamed
import org.lwjgl.opengl.GL11.GL_TEXTURE_1D
import org.lwjgl.opengl.GL11.GL_TEXTURE_2D
import org.lwjgl.opengl.GL12.GL_TEXTURE_3D
import org.lwjgl.opengl.GL30.*
import org.lwjgl.opengl.GL31.GL_TEXTURE_BUFFER
import org.lwjgl.opengl.GL31.GL_TEXTURE_RECTANGLE
import org.lwjgl.opengl.GL40.*

enum class TextureType(
    @JvmField
    val glId: Int,
    @JvmField
    val bindingId: Int
) : GlNamed {
    TEXTURE_1D(GL_TEXTURE_1D, GL_TEXTURE_BINDING_1D),
    TEXTURE_2D(GL_TEXTURE_2D, GL_TEXTURE_BINDING_2D),
    TEXTURE_3D(GL_TEXTURE_3D, GL_TEXTURE_BINDING_3D),
    TEXTURE_1D_ARRAY(GL_TEXTURE_1D_ARRAY, GL_TEXTURE_BINDING_1D_ARRAY),
    TEXTURE_2D_ARRAY(GL_TEXTURE_2D_ARRAY, GL_TEXTURE_BINDING_2D_ARRAY),
    TEXTURE_RECTANGLE(GL_TEXTURE_RECTANGLE, GL_TEXTURE_BINDING_RECTANGLE),
    TEXTURE_CUBE_MAP(GL_TEXTURE_CUBE_MAP, GL_TEXTURE_BINDING_CUBE_MAP),
    TEXTURE_CUBE_MAP_ARRAY(GL_TEXTURE_CUBE_MAP_ARRAY, GL_TEXTURE_BINDING_CUBE_MAP_ARRAY),
    TEXTURE_2D_MULTISAMPLE(GL_TEXTURE_2D_MULTISAMPLE, GL_TEXTURE_BINDING_2D_MULTISAMPLE),
    TEXTURE_2D_MULTISAMPLE_ARRAY(GL_TEXTURE_2D_MULTISAMPLE_ARRAY, GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY),
    TEXTURE_BUFFER(GL_TEXTURE_BUFFER, GL_TEXTURE_BINDING_BUFFER);

    override fun glId() = glId
}