#[Big Shot Lib] Cached dependency versions. Run the updateDependencyVersions task to update them all to latest.
#Wed Jul 15 16:57:14 MDT 2026
kotlin-for-forge=uhJhCT7X
neoforge-loader=21.6.20-beta
sodium=q6wdZywr
