package net.typho.big_shot_lib.api.client.rendering.opengl.constant

import org.lwjgl.opengl.GL11.*

enum class GlAttribMask(
    override val glId: Int
) : GlConstant {
    CURRENT_BIT(GL_CURRENT_BIT),
    POINT_BIT(GL_POINT_BIT),
    LINE_BIT(GL_LINE_BIT),
    POLYGON_BIT(GL_POLYGON_BIT),
    POLYGON_STIPPLE_BIT(GL_POLYGON_STIPPLE_BIT),
    PIXEL_MODE_BIT(GL_PIXEL_MODE_BIT),
    LIGHTING_BIT(GL_LIGHTING_BIT),
    FOG_BIT(GL_FOG_BIT),
    DEPTH_BUFFER_BIT(GL_DEPTH_BUFFER_BIT),
    ACCUM_BUFFER_BIT(GL_ACCUM_BUFFER_BIT),
    STENCIL_BUFFER_BIT(GL_STENCIL_BUFFER_BIT),
    VIEWPORT_BIT(GL_VIEWPORT_BIT),
    TRANSFORM_BIT(GL_TRANSFORM_BIT),
    ENABLE_BIT(GL_ENABLE_BIT),
    COLOR_BUFFER_BIT(GL_COLOR_BUFFER_BIT),
    HINT_BIT(GL_HINT_BIT),
    EVAL_BIT(GL_EVAL_BIT),
    LIST_BIT(GL_LIST_BIT),
    TEXTURE_BIT(GL_TEXTURE_BIT),
    SCISSOR_BIT(GL_SCISSOR_BIT),
    ALL_ATTRIB_BITS(GL_ALL_ATTRIB_BITS)
}