#[Big Shot Lib] Cached dependency versions. Run the updateDependencyVersions task to update them all to latest.
#Wed Jul 15 16:57:00 MDT 2026
kotlin-for-forge=WSKgpZoB
neoforge-loader=21.11.44
sodium=fyQ1HOA0
