#[Big Shot Lib] Cached dependency versions. Run the updateDependencyVersions task to update them all to latest.
#Tue Jul 14 21:27:46 MDT 2026
kotlin-for-forge=WSKgpZoB
neoforge-loader=21.11.42
sodium=fyQ1HOA0
