package net.typho.big_shot_lib.api.client.opengl.util

import org.lwjgl.opengl.GL11.GL_TEXTURE_1D
import org.lwjgl.opengl.GL11.GL_TEXTURE_2D
import org.lwjgl.opengl.GL12.GL_TEXTURE_3D
import org.lwjgl.opengl.GL30.*
import org.lwjgl.opengl.GL31.GL_TEXTURE_BUFFER
import org.lwjgl.opengl.GL31.GL_TEXTURE_RECTANGLE
import org.lwjgl.opengl.GL40.*

enum class TextureType(
    override val glId: Int,
    @JvmField
    val bindingId: Int,
    @JvmField
    val multisample: Boolean
) : GlNamed {
    TEXTURE_1D(GL_TEXTURE_1D, GL_TEXTURE_BINDING_1D, false),
    TEXTURE_2D(GL_TEXTURE_2D, GL_TEXTURE_BINDING_2D, false),
    TEXTURE_3D(GL_TEXTURE_3D, GL_TEXTURE_BINDING_3D, false),
    TEXTURE_1D_ARRAY(GL_TEXTURE_1D_ARRAY, GL_TEXTURE_BINDING_1D_ARRAY, false),
    TEXTURE_2D_ARRAY(GL_TEXTURE_2D_ARRAY, GL_TEXTURE_BINDING_2D_ARRAY, false),
    TEXTURE_RECTANGLE(GL_TEXTURE_RECTANGLE, GL_TEXTURE_BINDING_RECTANGLE, false),
    TEXTURE_CUBE_MAP(GL_TEXTURE_CUBE_MAP, GL_TEXTURE_BINDING_CUBE_MAP, false),
    TEXTURE_CUBE_MAP_ARRAY(GL_TEXTURE_CUBE_MAP_ARRAY, GL_TEXTURE_BINDING_CUBE_MAP_ARRAY, false),
    TEXTURE_2D_MULTISAMPLE(GL_TEXTURE_2D_MULTISAMPLE, GL_TEXTURE_BINDING_2D_MULTISAMPLE, true),
    TEXTURE_2D_MULTISAMPLE_ARRAY(GL_TEXTURE_2D_MULTISAMPLE_ARRAY, GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY, true),
    TEXTURE_BUFFER(GL_TEXTURE_BUFFER, GL_TEXTURE_BINDING_BUFFER, false)
}