#[Big Shot Lib] Cached dependency versions. Run the updateDependencyVersions task to update them all to latest.
#Wed Jul 15 16:57:02 MDT 2026
fabric-api=UEjZZNue
fabric-language-kotlin=bdhiINYC
fabric-loader=0.19.3
sodium=rLBgU2jc
