#[Big Shot Lib] Cached dependency versions. Run the updateDependencyVersions task to update them all to latest.
#Tue Jul 14 21:28:03 MDT 2026
fabric-api=lOQ4tyDD
fabric-language-kotlin=Pd0xrHCw
fabric-loader=0.19.3
sodium=vf7UgZpC
