#[Big Shot Lib] Cached dependency versions. Run the updateDependencyVersions task to update them all to latest.
#Fri Jul 17 11:13:21 MDT 2026
fabric-api=uLkEd5dr
fabric-language-kotlin=bdhiINYC
fabric-loader=0.19.3
sodium=vf7UgZpC
