#[Big Shot Lib] Cached dependency versions. Run the updateDependencyVersions task to update them all to latest.
#Wed Jul 15 11:03:22 MDT 2026
kotlin-for-forge=uhJhCT7X
neoforge-loader=21.1.236
sodium=S3DUMfBo
