#[Big Shot Lib] Cached dependency versions. Run the updateDependencyVersions task to update them all to latest.
#Fri Jul 17 11:13:22 MDT 2026
kotlin-for-forge=WSKgpZoB
neoforge-loader=26.2.0.23-beta
sodium=KHPycol7
