#[Big Shot Lib] Cached dependency versions. Run the updateDependencyVersions task to update them all to latest.
#Mon Jul 27 13:20:18 MDT 2026
kotlin-for-forge=WSKgpZoB
neoforge-loader=26.2.0.35-beta
sodium=KHPycol7
