modLoader = "kotlinforforge"
loaderVersion = "*"
issueTrackerURL="https://github.com/TheTypholorian/big_shot_lib/issues/"
logoFile="icon.png"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
logoFile = "icon.png"
authors = "${authors}"
description = '''${description}'''
