#[Big Shot Lib] Cached dependency versions. Run the updateDependencyVersions task to update them all to latest.
#Wed Jul 15 16:56:49 MDT 2026
fabric-api=8GVp7wDk
fabric-language-kotlin=bdhiINYC
fabric-loader=0.19.3
sodium=pmgeU5yX
