package net.typho.big_shot_lib.api.client.opengl.shaders.variables

import net.typho.big_shot_lib.api.client.opengl.util.GlNamed
import net.typho.big_shot_lib.api.client.opengl.util.TextureType
import org.lwjgl.opengl.GL11.*
import org.lwjgl.opengl.GL20.*
import org.lwjgl.opengl.GL21.*
import org.lwjgl.opengl.GL30.*
import org.lwjgl.opengl.GL31.*
import org.lwjgl.opengl.GL32.*
import org.lwjgl.opengl.GL40.*
import org.lwjgl.opengl.GL42.*

enum class ShaderVariableType(
    override val glId: Int,
    @JvmField
    val category: Category
) : GlNamed {
    FLOAT(GL_FLOAT, Category.PRIMITIVE),
    FLOAT_VEC2(GL_FLOAT_VEC2, Category.VECTOR),
    FLOAT_VEC3(GL_FLOAT_VEC3, Category.VECTOR),
    FLOAT_VEC4(GL_FLOAT_VEC4, Category.VECTOR),

    INT(GL_INT, Category.PRIMITIVE),
    INT_VEC2(GL_INT_VEC2, Category.VECTOR),
    INT_VEC3(GL_INT_VEC3, Category.VECTOR),
    INT_VEC4(GL_INT_VEC4, Category.VECTOR),

    UINT(GL_UNSIGNED_INT, Category.PRIMITIVE),
    UINT_VEC2(GL_UNSIGNED_INT_VEC2, Category.VECTOR),
    UINT_VEC3(GL_UNSIGNED_INT_VEC3, Category.VECTOR),
    UINT_VEC4(GL_UNSIGNED_INT_VEC4, Category.VECTOR),

    BOOL(GL_BOOL, Category.PRIMITIVE),
    BOOL_VEC2(GL_BOOL_VEC2, Category.VECTOR),
    BOOL_VEC3(GL_BOOL_VEC3, Category.VECTOR),
    BOOL_VEC4(GL_BOOL_VEC4, Category.VECTOR),

    MAT2(GL_FLOAT_MAT2, Category.MATRIX),
    MAT2X2(GL_FLOAT_MAT2x3, Category.MATRIX),
    MAT2X4(GL_FLOAT_MAT2x4, Category.MATRIX),
    MAT3(GL_FLOAT_MAT3, Category.MATRIX),
    MAT3X2(GL_FLOAT_MAT3x2, Category.MATRIX),
    MAT3X4(GL_FLOAT_MAT3x4, Category.MATRIX),
    MAT4(GL_FLOAT_MAT4, Category.MATRIX),
    MAT4X2(GL_FLOAT_MAT4x2, Category.MATRIX),
    MAT4X3(GL_FLOAT_MAT4x3, Category.MATRIX),

    SAMPLER_1D(GL_SAMPLER_1D, Category.SAMPLER),
    SAMPLER_2D(GL_SAMPLER_2D, Category.SAMPLER),
    SAMPLER_3D(GL_SAMPLER_3D, Category.SAMPLER),
    SAMPLER_2D_RECT(GL_SAMPLER_2D_RECT, Category.SAMPLER),
    SAMPLER_1D_ARRAY(GL_SAMPLER_1D_ARRAY, Category.SAMPLER),
    SAMPLER_2D_ARRAY(GL_SAMPLER_2D_ARRAY, Category.SAMPLER),
    SAMPLER_CUBE(GL_SAMPLER_CUBE, Category.SAMPLER),
    SAMPLER_BUFFER(GL_SAMPLER_BUFFER, Category.SAMPLER),
    SAMPLER_CUBE_MAP_ARRAY(GL_SAMPLER_CUBE_MAP_ARRAY, Category.SAMPLER),
    SAMPLER_2D_MULTISAMPLE(GL_SAMPLER_2D_MULTISAMPLE, Category.SAMPLER),
    SAMPLER_2D_MULTISAMPLE_ARRAY(GL_SAMPLER_2D_MULTISAMPLE_ARRAY, Category.SAMPLER),

    INT_SAMPLER_1D(GL_INT_SAMPLER_1D, Category.SAMPLER),
    INT_SAMPLER_2D(GL_INT_SAMPLER_2D, Category.SAMPLER),
    INT_SAMPLER_3D(GL_INT_SAMPLER_3D, Category.SAMPLER),
    INT_SAMPLER_2D_RECT(GL_INT_SAMPLER_2D_RECT, Category.SAMPLER),
    INT_SAMPLER_1D_ARRAY(GL_INT_SAMPLER_1D_ARRAY, Category.SAMPLER),
    INT_SAMPLER_2D_ARRAY(GL_INT_SAMPLER_2D_ARRAY, Category.SAMPLER),
    INT_SAMPLER_CUBE(GL_INT_SAMPLER_CUBE, Category.SAMPLER),
    INT_SAMPLER_BUFFER(GL_INT_SAMPLER_BUFFER, Category.SAMPLER),
    INT_SAMPLER_CUBE_MAP_ARRAY(GL_INT_SAMPLER_CUBE_MAP_ARRAY, Category.SAMPLER),
    INT_SAMPLER_2D_MULTISAMPLE(GL_INT_SAMPLER_2D_MULTISAMPLE, Category.SAMPLER),
    INT_SAMPLER_2D_MULTISAMPLE_ARRAY(GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY, Category.SAMPLER),

    UINT_SAMPLER_1D(GL_UNSIGNED_INT_SAMPLER_1D, Category.SAMPLER),
    UINT_SAMPLER_2D(GL_UNSIGNED_INT_SAMPLER_2D, Category.SAMPLER),
    UINT_SAMPLER_3D(GL_UNSIGNED_INT_SAMPLER_3D, Category.SAMPLER),
    UINT_SAMPLER_2D_RECT(GL_UNSIGNED_INT_SAMPLER_2D_RECT, Category.SAMPLER),
    UINT_SAMPLER_1D_ARRAY(GL_UNSIGNED_INT_SAMPLER_1D_ARRAY, Category.SAMPLER),
    UINT_SAMPLER_2D_ARRAY(GL_UNSIGNED_INT_SAMPLER_2D_ARRAY, Category.SAMPLER),
    UINT_SAMPLER_CUBE(GL_UNSIGNED_INT_SAMPLER_CUBE, Category.SAMPLER),
    UINT_SAMPLER_BUFFER(GL_UNSIGNED_INT_SAMPLER_BUFFER, Category.SAMPLER),
    UINT_SAMPLER_CUBE_MAP_ARRAY(GL_UNSIGNED_INT_SAMPLER_CUBE_MAP_ARRAY, Category.SAMPLER),
    UINT_SAMPLER_2D_MULTISAMPLE(GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE, Category.SAMPLER),
    UINT_SAMPLER_2D_MULTISAMPLE_ARRAY(GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY, Category.SAMPLER),

    SAMPLER_1D_SHADOW(GL_SAMPLER_1D_SHADOW, Category.SAMPLER),
    SAMPLER_2D_SHADOW(GL_SAMPLER_2D_SHADOW, Category.SAMPLER),
    SAMPLER_2D_RECT_SHADOW(GL_SAMPLER_2D_RECT_SHADOW, Category.SAMPLER),
    SAMPLER_1D_ARRAY_SHADOW(GL_SAMPLER_1D_ARRAY_SHADOW, Category.SAMPLER),
    SAMPLER_2D_ARRAY_SHADOW(GL_SAMPLER_2D_ARRAY_SHADOW, Category.SAMPLER),
    SAMPLER_CUBE_SHADOW(GL_SAMPLER_CUBE_SHADOW, Category.SAMPLER),
    SAMPLER_CUBE_MAP_ARRAY_SHADOW(GL_SAMPLER_CUBE_MAP_ARRAY_SHADOW, Category.SAMPLER),

    IMAGE_1D(GL_IMAGE_1D, Category.IMAGE),
    IMAGE_2D(GL_IMAGE_2D, Category.IMAGE),
    IMAGE_3D(GL_IMAGE_3D, Category.IMAGE),
    IMAGE_2D_RECT(GL_IMAGE_2D_RECT, Category.IMAGE),
    IMAGE_CUBE(GL_IMAGE_CUBE, Category.IMAGE),
    IMAGE_BUFFER(GL_IMAGE_BUFFER, Category.IMAGE),
    IMAGE_1D_ARRAY(GL_IMAGE_1D_ARRAY, Category.IMAGE),
    IMAGE_2D_ARRAY(GL_IMAGE_2D_ARRAY, Category.IMAGE),
    IMAGE_CUBE_MAP_ARRAY(GL_IMAGE_CUBE_MAP_ARRAY, Category.IMAGE),
    IMAGE_2D_MULTISAMPLE(GL_IMAGE_2D_MULTISAMPLE, Category.IMAGE),
    IMAGE_2D_MULTISAMPLE_ARRAY(GL_IMAGE_2D_MULTISAMPLE_ARRAY, Category.IMAGE),

    INT_IMAGE_1D(GL_INT_IMAGE_1D, Category.IMAGE),
    INT_IMAGE_2D(GL_INT_IMAGE_2D, Category.IMAGE),
    INT_IMAGE_3D(GL_INT_IMAGE_3D, Category.IMAGE),
    INT_IMAGE_2D_RECT(GL_INT_IMAGE_2D_RECT, Category.IMAGE),
    INT_IMAGE_CUBE(GL_INT_IMAGE_CUBE, Category.IMAGE),
    INT_IMAGE_BUFFER(GL_INT_IMAGE_BUFFER, Category.IMAGE),
    INT_IMAGE_1D_ARRAY(GL_INT_IMAGE_1D_ARRAY, Category.IMAGE),
    INT_IMAGE_2D_ARRAY(GL_INT_IMAGE_2D_ARRAY, Category.IMAGE),
    INT_IMAGE_CUBE_MAP_ARRAY(GL_INT_IMAGE_CUBE_MAP_ARRAY, Category.IMAGE),
    INT_IMAGE_2D_MULTISAMPLE(GL_INT_IMAGE_2D_MULTISAMPLE, Category.IMAGE),
    INT_IMAGE_2D_MULTISAMPLE_ARRAY(GL_INT_IMAGE_2D_MULTISAMPLE_ARRAY, Category.IMAGE),

    UNSIGNED_INT_IMAGE_1D(GL_UNSIGNED_INT_IMAGE_1D, Category.IMAGE),
    UNSIGNED_INT_IMAGE_2D(GL_UNSIGNED_INT_IMAGE_2D, Category.IMAGE),
    UNSIGNED_INT_IMAGE_3D(GL_UNSIGNED_INT_IMAGE_3D, Category.IMAGE),
    UNSIGNED_INT_IMAGE_2D_RECT(GL_UNSIGNED_INT_IMAGE_2D_RECT, Category.IMAGE),
    UNSIGNED_INT_IMAGE_CUBE(GL_UNSIGNED_INT_IMAGE_CUBE, Category.IMAGE),
    UNSIGNED_INT_IMAGE_BUFFER(GL_UNSIGNED_INT_IMAGE_BUFFER, Category.IMAGE),
    UNSIGNED_INT_IMAGE_1D_ARRAY(GL_UNSIGNED_INT_IMAGE_1D_ARRAY, Category.IMAGE),
    UNSIGNED_INT_IMAGE_2D_ARRAY(GL_UNSIGNED_INT_IMAGE_2D_ARRAY, Category.IMAGE),
    UNSIGNED_INT_IMAGE_CUBE_MAP_ARRAY(GL_UNSIGNED_INT_IMAGE_CUBE_MAP_ARRAY, Category.IMAGE),
    UNSIGNED_INT_IMAGE_2D_MULTISAMPLE(GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE, Category.IMAGE),
    UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY(GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY, Category.IMAGE);

    fun expectedTextureType(): TextureType {
        return when (this) {
            SAMPLER_1D, INT_SAMPLER_1D, UINT_SAMPLER_1D, SAMPLER_1D_SHADOW,
            IMAGE_1D, INT_IMAGE_1D, UNSIGNED_INT_IMAGE_1D -> TextureType.TEXTURE_1D

            SAMPLER_1D_ARRAY, INT_SAMPLER_1D_ARRAY, UINT_SAMPLER_1D_ARRAY, SAMPLER_1D_ARRAY_SHADOW,
            IMAGE_1D_ARRAY, INT_IMAGE_1D_ARRAY, UNSIGNED_INT_IMAGE_1D_ARRAY -> TextureType.TEXTURE_1D_ARRAY

            SAMPLER_2D, INT_SAMPLER_2D, UINT_SAMPLER_2D, SAMPLER_2D_SHADOW,
            IMAGE_2D, INT_IMAGE_2D, UNSIGNED_INT_IMAGE_2D -> TextureType.TEXTURE_2D

            SAMPLER_2D_ARRAY, INT_SAMPLER_2D_ARRAY, UINT_SAMPLER_2D_ARRAY, SAMPLER_2D_ARRAY_SHADOW,
            IMAGE_2D_ARRAY, INT_IMAGE_2D_ARRAY, UNSIGNED_INT_IMAGE_2D_ARRAY -> TextureType.TEXTURE_2D_ARRAY

            SAMPLER_2D_RECT, INT_SAMPLER_2D_RECT, UINT_SAMPLER_2D_RECT, SAMPLER_2D_RECT_SHADOW,
            IMAGE_2D_RECT, INT_IMAGE_2D_RECT, UNSIGNED_INT_IMAGE_2D_RECT -> TextureType.TEXTURE_RECTANGLE

            SAMPLER_3D, INT_SAMPLER_3D, UINT_SAMPLER_3D,
            IMAGE_3D, INT_IMAGE_3D, UNSIGNED_INT_IMAGE_3D -> TextureType.TEXTURE_3D

            SAMPLER_CUBE, SAMPLER_CUBE_SHADOW,
            IMAGE_CUBE, INT_IMAGE_CUBE, UNSIGNED_INT_IMAGE_CUBE,
            INT_SAMPLER_CUBE, UINT_SAMPLER_CUBE -> TextureType.TEXTURE_CUBE_MAP

            SAMPLER_CUBE_MAP_ARRAY, SAMPLER_CUBE_MAP_ARRAY_SHADOW,
            IMAGE_CUBE_MAP_ARRAY, INT_IMAGE_CUBE_MAP_ARRAY, UNSIGNED_INT_IMAGE_CUBE_MAP_ARRAY,
            INT_SAMPLER_CUBE_MAP_ARRAY, UINT_SAMPLER_CUBE_MAP_ARRAY -> TextureType.TEXTURE_CUBE_MAP_ARRAY

            SAMPLER_2D_MULTISAMPLE, IMAGE_2D_MULTISAMPLE,
            INT_IMAGE_2D_MULTISAMPLE, UNSIGNED_INT_IMAGE_2D_MULTISAMPLE,
            INT_SAMPLER_2D_MULTISAMPLE, UINT_SAMPLER_2D_MULTISAMPLE -> TextureType.TEXTURE_2D_MULTISAMPLE

            SAMPLER_2D_MULTISAMPLE_ARRAY, IMAGE_2D_MULTISAMPLE_ARRAY,
            INT_IMAGE_2D_MULTISAMPLE_ARRAY, UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY,
            INT_SAMPLER_2D_MULTISAMPLE_ARRAY, UINT_SAMPLER_2D_MULTISAMPLE_ARRAY -> TextureType.TEXTURE_2D_MULTISAMPLE_ARRAY

            SAMPLER_BUFFER, INT_SAMPLER_BUFFER, UINT_SAMPLER_BUFFER,
            IMAGE_BUFFER, INT_IMAGE_BUFFER, UNSIGNED_INT_IMAGE_BUFFER -> TextureType.TEXTURE_BUFFER

            else -> throw UnsupportedOperationException()
        }
    }

    enum class Category {
        PRIMITIVE,
        VECTOR,
        MATRIX,
        SAMPLER,
        IMAGE
    }
}